---
- name: Gereksinimlerin indirilmesi
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: GPG key'in indirilmesi
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker repolarının indirilmesi
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Docker engine, docker cli ve containerd.io kurulması
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
- name: docker servisini başlatma
  service:
    name: docker
    state: started
    enabled: yes

- name: docker restart etme
  service:
    name: docker
    state: restarted
